# Generated by Django 2.1.1 on 2018-10-05 03:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('publishdate', models.DateTimeField(default=datetime.datetime(2018, 10, 5, 3, 27, 50, 195925), verbose_name='发布日期')),
                ('detail', models.CharField(max_length=5000, verbose_name='文章内容')),
                ('pic', models.ImageField(upload_to='uploads', verbose_name='图片')),
            ],
            options={
                'verbose_name': '新闻文章',
                'verbose_name_plural': '新闻文章',
            },
        ),
    ]
